eHouseManager.Web/Controllers/ApartmentController.cs
using eHouseManager.Common;
using eHouseManager.Services.Contracts;
using eHouseManager.Web.Attributes;
using eHouseManager.Web.Mappers;
using eHouseManager.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace eHouseManager.Web.Controllers
{
    public class ApartmentController : Controller
    {
        private readonly IApartmentService _as;
        private readonly ITaxPaymentService _tps;
        public ApartmentController(IApartmentService @as, ITaxPaymentService tps)
        {
            _as = @as;
            _tps = tps;
        }

        [Authorize(Roles = Constants.ROLE_USER)]
        public IActionResult UserInfo()
        {
            var userId = int.Parse(this.HttpContext.Session.GetString(Constants.SESSION_ID_KEY));

            var apartmentInfo = _as.GetAllByUserId(userId).Select(x => x.GetUserApartmentModel());

            return View(apartmentInfo);
        }

        [HttpGet]
        [Authorize(Roles = Constants.ROLE_USER)]
        public FileResult Export(int id)
        {
            var lastTaxPayment = _tps.GetById(id);
            var sb = new StringBuilder();

            sb.AppendLine($"Year:, {lastTaxPayment.Year},");
            sb.AppendLine($"Month:, {lastTaxPayment.Month},");
            sb.AppendLine($"Paid On:, {lastTaxPayment.PaidOn},");
            sb.AppendLine($"Amount:, {lastTaxPayment.Amount}");

            return File(Encoding.UTF8.GetBytes(sb.ToString()), "text/csv", "Payment.csv");
        }

        [Authorize(Roles = Constants.ROLE_EMPLOYEE)]
        public IActionResult Index()
        {

            var apartmentInfo = _as.GetAll().Select(x => x.GetAllApartmentModel());

            return View(apartmentInfo);
        }

        [Authorize(Roles = Constants.ROLE_EMPLOYEE)]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = Constants.ROLE_EMPLOYEE)]
        [HttpPost]
        public IActionResult Create(UserApartmentViewModel model)
        {

            _as.Post(model.GetCreateApartmentDTO());
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = Constants.ROLE_EMPLOYEE)]
        public IActionResult Update(int id)
        {
            var model = _as.GetById(id);
            return View(model.GetUpdateApartmentModel());
        }

        [Authorize(Roles = Constants.ROLE_EMPLOYEE)]
        [HttpPost]
        public IActionResult Update(int id, UserApartmentViewModel model)
        {
            _as.Update(id, model.GetUpdateApartmentDTO());
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = Constants.ROLE_EMPLOYEE)]
        public IActionResult Delete(int id)
        {
            _as.Delete(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

eHouseManager.Web/Controllers/AuthController.cs
using eHouseManager.Common;
using eHouseManager.Services.Contracts;
using eHouseManager.Web.Attributes;
using eHouseManager.Web.Mappers;
using eHouseManager.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eHouseManager.Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _auth;
        private readonly IUserService _us;
        public AuthController(IAuthService auth, IUserService us)
        {
            _auth = auth;
            _us = us;
        }
        public IActionResult Login()
        {
            var loginViewModel = new LoginViewModel();

            return this.View(loginViewModel);
        }

        //POST: /auth/login
        [HttpPost]
        public IActionResult Login(LoginViewModel loginViewModel)
        {
            if (!_auth.IsExistingEmail(loginViewModel.Email))
            {
                this.ModelState.AddModelError("Email", "User with this email address doesn't exists.");
                return this.View(loginViewModel);
            }

            if (!_auth.IsPasswordValid(loginViewModel.Email, loginViewModel.Password))
            {
                this.ModelState.AddModelError("Password", "Wrong Password!");
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(loginViewModel);
            }

            var credentials = $"{loginViewModel.Email} {loginViewModel.Password}";

            var user = _auth.FindUser(loginViewModel.Email, loginViewModel.Password);
            if (user is null)
            {
                this.ModelState.AddModelError("Username", "Invalid input data");
                return this.View(loginViewModel);
            }
            else
            {
                this.HttpContext.Session.SetString(Constants.SESSION_AUTH_KEY, credentials);
                this.HttpContext.Session.SetString(Constants.SESSION_ROLE_KEY, user.Role);
                this.HttpContext.Session.SetString(Constants.SESSION_ID_KEY, user.Id.ToString());

                return this.RedirectToAction("Index", "Home");
            }
        }


        //GET: /auth/logout
        public IActionResult Logout()
        {
            this.HttpContext.Session.Remove(Constants.SESSION_AUTH_KEY);

            return this.RedirectToAction("index", "home");
        }

        [HttpGet]
        public IActionResult Register()
        {
            var model = new UserViewModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult Register(UserViewModel model)
        {
            if ( _auth.IsExistingEmail(model.Email))
            {
                this.ModelState.AddModelError("Email", "User with this email address already exists.");
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            _us.Post(model.GetDTOFromModel());

            return this.Redirect(nameof(Login));
        }


        [Authorize(Roles = Constants.ROLE_USER)]
        public ActionResult Settings()
        {
            var userId = int.Parse(this.HttpContext.Session.GetString(Constants.SESSION_ID_KEY));

            var user = _us.GetById(userId);

            return View(user.GetSettingsModel());
        }

        [Authorize(Roles = Constants.ROLE_USER)]
        //POST: /auth/settings
        [HttpPost]
        public IActionResult Settings(SettingsViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            var userId = int.Parse(this.HttpContext.Session.GetString(Constants.SESSION_ID_KEY));

            _us.Update(userId, model.GetDTOFromSettingsModel());

            return this.RedirectToAction("Index", "Home");
        }
    }
}

eHouseManager.Web/Controllers/EventController.cs
using eHouseManager.Common;
using eHouseManager.Services.Contracts;
using eHouseManager.Web.Attributes;
using eHouseManager.Web.Mappers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eHouseManager.Web.Controllers
{
    public class EventController : Controller
    {
        private readonly IEventService _es;

        public EventController(IEventService es)
        {
            _es = es;
        }

        [Authorize(Roles = Constants.ROLE_USER)]
        public IActionResult UserInfo()
        {
            var userId = int.Parse(this.HttpContext.Session.GetString(Constants.SESSION_ID_KEY));

            var result = _es.GetAllByUserId(userId).Select(x => x.GetEventModel());

            return View(result);
        }


    }
}

eHouseManager.Web/Views/Shared/_Layout.cshtml
@{
    this.ViewData[Constants.SESSION_AUTH_KEY] = this.Context.Session.Keys.Contains(Constants.SESSION_AUTH_KEY);
    this.ViewData[Constants.SESSION_ROLE_KEY] = this.Context.Session.GetString(Constants.SESSION_ROLE_KEY);
}
<!DOCTYPE html>

<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="eHouseManager">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700" rel="stylesheet">

    <title>eHouseManager</title>
    <link rel="icon" type="image/png" href="@Constants.DOMAIN_NAME/images/favicon.png" />
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="~/css/fontawesome.css">
    <link rel="stylesheet" href="~/css/template.css">
    <link rel="stylesheet" href="~/css/owl.css">
    <link rel="stylesheet" href="~/css/site.css">
    @RenderSection("Styles", required: false)
</head>
<body>
    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
    <!-- ***** Preloader End ***** -->

    <header class="">
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid">
                <i class="fas fa-shipping-fast"></i>
                <a class="navbar-brand mr-auto" asp-controller="Home" asp-action="Index"><h2><sup>e</sup>House<sub>Manager</sub></h2></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse ml-auto" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li id="nav-home" class="nav-item active">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">
                                Начало
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li id="nav-about" class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="About">За нас</a>
                        </li>
                        @if ((bool)this.ViewData[Constants.SESSION_AUTH_KEY]
                            && this.ViewData[Constants.SESSION_ROLE_KEY].ToString() == Constants.ROLE_EMPLOYEE)
                            {

                                <li class="dropdown">
                                    <a class="nav-link dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="cursor:pointer;">
                                        Controller
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        <a asp-controller="Apartment" asp-action="Index" class="custom-dropdown-item">Create Apartment</a>
                                        <a asp-controller="Event" asp-action="AdminPanel" class="custom-dropdown-item">Events</a>
                                        
                                    </div>
                                </li>

                            }
                    </ul>
                </div>

                <div class="functional-buttons">
                    <ul>
                        @if (!(bool)this.ViewData[Constants.SESSION_AUTH_KEY])
                        {
                            <li><a asp-controller="Auth" asp-action="Login">Вход</a></li>
                            <li><a asp-controller="Auth" asp-action="Register">Регистрация</a></li>
                        }
                        else
                        {


                            @if (this.ViewData[Constants.SESSION_ROLE_KEY].ToString() == Constants.ROLE_USER)
                            {
                                <li><a asp-controller="Auth" asp-action="Settings">Настройки</a></li>

                                <li><a asp-controller="Apartment" asp-action="UserInfo" class="test-btn">Моите апартаменти</a></li>
                            }

                            <li><a asp-controller="Auth" asp-action="Logout">Изход</a></li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @RenderBody()


    <div class="modal" id="form-modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                </div>
                <div class="modal-body">

                </div>
            </div>
        </div>
    </div>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="footer-item">
                        <div class="footer-heading">
                            <h2>За нас</h2>
                        </div>
                        <p>Ние сме млад и иновативен екип, с амбиция да модернизираме начина, по който се управляват сградите в режим на Етажна Собственост (ЕС), да улесним прозрачността и споделянето на информация между обитателите на ЕС. Стремим се да откликнем на индивидуалните потребности на всеки клиент, стъпвайки върху добрите и утвърдили се практики от споделения опит на Управители на ЕС. Работата с нас Ви гарантира спокойствие, комфорт и максимален стремеж от наша страна за задоволяване на нуждите на вашата ЕС.</p>
                    </div>
                </div>

         


                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="footer-item">
                        <div class="footer-heading">
                            <h2>Полезни връзки</h2>
                        </div>
                        <ul class="footer-list">
                            <li><a href="https://www.mrrb.bg/bg/zakon-za-upravlenie-na-etajnata-sobstvenost/">ЗУЕС</a></li>
                            <li><a href="http://www.cez.bg/bg/home.html">ЧЕЗ България</a></li>
                            <li><a href="http://www.sofiyskavoda.bg/">Софийска вода</a></li>
                            <li><a href="https://toplo.bg/">Топлофикация София</a></li>

                        </ul>
                    </div>
                </div>

                <div class="col-md-3 col-sm-6 col-xs-12">
                    <div class="footer-item">
                        <div class="footer-heading">
                            <h2>Повече информация</h2>
                        </div>
                        <ul class="footer-list">
                            <li>Телефон <a href="#">010-020-0560</a></li>
                            <li>Ел.поща: <a href="#">mail@company.com</a></li>
                            <li>Подръжка <a href="#">support@company.com</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Ends Here -->
    <!-- Bootstrap core JavaScript -->
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Additional Scripts -->
    <script src="~/js/custom.js"></script>
    <script src="~/js/owl.js"></script>
    <script src="~/js/accordions.js"></script>


    <script language="text/Javascript">
        cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
        function clearField(t) {                   //declaring the array outside of the
            if (!cleared[t.id]) {                      // function makes it static and global
                cleared[t.id] = 1;  // you could use true and false, but that's more typing
                t.value = '';         // with more chance of typos
                t.style.color = '#fff';
            }
        }
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

eHouseManager.Web/Views/Shared/_LayoutEmpty.cshtml
@{
    this.ViewData[Constants.SESSION_AUTH_KEY] = this.Context.Session.Keys.Contains(Constants.SESSION_AUTH_KEY);
    this.ViewData[Constants.SESSION_ROLE_KEY] = this.Context.Session.GetString(Constants.SESSION_ROLE_KEY);
}
<!DOCTYPE html>

<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700" rel="stylesheet">

    <title>DeliverIT</title>

    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="~/css/fontawesome.css">
    <link rel="stylesheet" href="~/css/template.css">
    <link rel="stylesheet" href="~/css/owl.css">
    <link rel="stylesheet" href="~/css/site.css">
    @RenderSection("Styles", required: false)
</head>
<body>

    @RenderBody()

    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>

    <script src="~/js/custom.js"></script>
    <script src="~/js/owl.js"></script>
    <script src="~/js/accordions.js"></script>



    @RenderSection("Scripts", required: false)
</body>
</html>